# Docker Compose file to create Drupal CMS website with postgres DB

version: '3'

services:
    drupal:
        image: drupal:8-apache
        ports: 
            - 8080:80
        volumes: 
            -   drupal-modules:/var/www/html/modules
            -   drupal-profiles:/var/www/html/profiles
            -   drupal-themes:/var/www/html/themes
            -   drupal-sites:/var/www/html/sites
        restart: always
    postgres:
        image: postgres:10
        ports:
            - 5432:5432
        environment: 
            POSTGRES_USER: nived
            POSTGRES_PASSWORD: redhat
            POSTGRES_DB: webapp
        restart: always
volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-themes:
    drupal-sites: