# create your drupal and postgres config here, based off the last assignment
version: '3'

services: 
    drupal:
        build: .
        image: custom-drupal
        ports: 
            - 80:80
        volumes: 
            - drupal-modules:/var/www/html/modules
            - drupal-themes:/var/www/html/themes
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites 

    postgres:
        image: postgres:12.1
        volumes: 
            - drupal-data:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: nived
            POSTGRES_PASSWORD: redhat
            POSTGRES_DB: drupal
        ports: 
            -  5432:5432

volumes:
    drupal-modules:
    drupal-sites:
    drupal-themes:
    drupal-profiles:
    drupal-data: